### ISSUE TITLE
"Could not resolve the actual object type" error when `null` returned in list of interfaces

### ISSUE THREAD

**Issue by gao-artur** [ChilliCream/graphql-platform#3594]
Schema
```
type Query{
  test: [BaseType]
}
interface BaseType {
  name: ID!
}
type ConcreteType implements BaseType {
  name: ID!
}
```
Query
```
query {
  test {
    __typename
  }
}
```
Response
```
{
  "errors": [
    {
      "message": "Could not resolve the actual object type from `HotChocolate.Language.NullValueNode` for the abstract type `test`.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "test",
        0
      ]
    }
  ],
  "data": {
    "test": [
      null
    ]
  }
}
```

**Expected behavior**
`null` should be returned in list without errors.

**Additional context**
HC v11.2.2

**Comment by gao-artur** [comment]
Slack conversation
https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1619428143159200

**Comment by PascalSenn** [comment]
Hi @gao-artur  
I tried to reproduce the issue you described in #3626 but could not reporduce it in a test
cann you provide a repro of this issue?

**Comment by gao-artur** [comment]
Hi @PascalSenn 
Was able to reproduce it only when using stitching. Please see repo here
https://github.com/gao-artur/graphql-stitching-3594

**Comment by gao-artur** [comment]
Hi @PascalSenn 
I just tried to debug this issue and that's what I found:

When the remote schema executor reaches [this line](https://github.com/ChilliCream/hotchocolate/blob/develop/src/HotChocolate/Core/src/Execution/Processing/ValueCompletion.cs#L37) the `result` is `null`:
![image](https://user-images.githubusercontent.com/4518483/120104345-b0a9c480-c15c-11eb-9db7-b9237a13356e.png)

But when stitching schema executor reaches same line the result is `NullValueNode`:
![image](https://user-images.githubusercontent.com/4518483/120107047-1485ba80-c168-11eb-976f-41c68b95d693.png)

Would this be the correct fix for the bug?
```
if (result is null || result is NullValueNode)
{
    completedResult = null;
    return true;
}
```

**Comment by michaelstaib** [comment]
this is fixed with 4064

**Comment by gao-artur** [comment]
@michaelstaib what version should I use to verify the fix? I just tried `12.0.0-rc.11` but the issue still reproduced.

**Comment by gao-artur** [comment]
Still reproduced with stable `12.8.2` and latest `13.0.0-preview.19`.

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.

You can join the preview of Hot Chocolate Fusion now on Slack
