### ISSUE TITLE
Using pagination and cursor with where filter skips records 'randomly'

### ISSUE THREAD

**Issue by Dikarabo-Molele** [ChilliCream/graphql-platform#5450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I am currently experiencing an issue where I have setup a Query on an entity with UsePaging and UseSorting annotations and when trying to use the endCursor, some records are skipped 'randomly'

Example query:
`query controlsByListOfPropsCursor($filerIdsIds: [String]!, $afterSting: String){
    controls(after:$afterSting, where: {filerIdsIds: {in: $sourceSystemRecordIds}})
    {
       nodes
       {
            prop1,
            prop2,
            prop3
       },
       pageInfo
       {
           hasNextPage,
           endCursor
       }
    }
}`

Query Setup:

![image](https://user-images.githubusercontent.com/25633424/193214765-c401d16e-71b7-4fbf-aa3c-1e4d61549690.png)

Code to call query until all results fetched:

![image](https://user-images.githubusercontent.com/25633424/193214172-2d8eb490-9663-4cf7-910f-2de03a8e922c.png)

Not sure if there is something missing on my setup that should maintain ordering?

### Steps to reproduce

1. Run query with after == null value
2. Fetch results x number of times using after == endCursor until hasNextPage == false

### Product

Strawberry Shake

### Version

11.3.7

**Comment by michaelstaib** [comment]
Can you check with the latest version 12? As far as I can remember we fixed this particular issue.

**Comment by Dikarabo-Molele** [comment]
> Can you check with the latest version 12? As far as I can remember we fixed this particular issue.

@michaelstaib, managed to do the upgrade and the issue still persists

**Comment by d-lundy** [comment]
I'm seeing this issue in 12.15.0 as well.

**Comment by michaelstaib** [comment]
Thanks for the feedback ... we will look into this.

**Comment by glen-84** [comment]
@Dikarabo-Molele Please add a link to a minimal reproduction of this issue.

**Comment by glen-84** [comment]
Closing, for lack of a minimal reproduction.
